services:
  lumen:
    build: .
    container_name: lumen
    ports:
      - "8081:8080"
    environment:
      APP_VERSION: "2.0.0"
      ENV_NAME: "TEST-TEST"
      OTEL_SERVICE_NAME: "lumen"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
      OTEL_TRACES_EXPORTER: "otlp"

  prometheus:
    image: prom/prometheus:v3.8.1
    container_name: prometheus
    volumes:
      - ./obs-stack-config/prometheus-config.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    # command:
    #   - "--web.enable-remote-write-receiver"


  loki:
    image: grafana/loki:3.6.3
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./obs-stack-config/loki-config.yaml:/etc/loki/local-config.yaml
    command:
      - "-config.file=/etc/loki/local-config.yaml"

  alloy:
    image: grafana/alloy:v1.12.1
    container_name: alloy
    volumes:
      - ./obs-stack-config/alloy-config.alloy:/etc/alloy/config.alloy
      # does work since docker runs inside vm (colima here)
      - /var/lib/docker/containers:/var/lib/docker/containers:ro

  grafana:
    image: grafana/grafana:12.3.1
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_USERS_DEFAULT_THEME=light
    volumes:
      - ./obs-stack-config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/grafana-datasources.yaml

