spring:
  application:
    name: "lumen"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: "lumen"

lumen:
  petstore:
    url: "http://localhost:4444"
    api-key: "testkey"